<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>feeTable</name>
   <tag></tag>
   <elementGuidId>6f90964a-a238-428c-a6d1-0ed1b751a261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
